name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
      working-directory: react-web
    - run: yarn build
      working-directory: react-web

    - name: build debian package
      run: make build-package
