name: CI
on:
  push:
    branches: [ master ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
      working-directory: react-web

    - name: build debian package
      run: echo not implemented
        
