# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn build
      working-directory: react-web  

  build-deb-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: build debian package
        run: echo not implemented
        
