name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.15'

      - name: build debian package
        run: make build-deps prepare-package
